version: '3.8'

services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:hisamo3485043@mysql:3306/platform?charset=utf8mb4"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hisamo3485043
      MYSQL_DATABASE: platform
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
